///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                      THIS FILE WAS AUTO-GENERATED BY VUENGINE IDE - DO NOT EDIT                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////


//---------------------------------------------------------------------------------------------------------
//												INCLUDES
//---------------------------------------------------------------------------------------------------------

#include <I18n.h>


//---------------------------------------------------------------------------------------------------------
//												DECLARATIONS
//---------------------------------------------------------------------------------------------------------

extern EntitySpec FLAG_FRANCE_EN;


//---------------------------------------------------------------------------------------------------------
//												DEFINITIONS
//---------------------------------------------------------------------------------------------------------

/*
 * IMPORTANT: Ensure that this file is encoded in Windows-1252 or ISO-8859-1 ("ANSI") to make use
 * of the full extended ASCII character set including special characters of European languages.
 *
 * The following character is meant to prevent editors from loading this file as UTF-8, since it doesn't
 * form part of a valid UTF-8 byte sequence: ý
 */

const char* const LANGUAGE_FR_STRINGS[] =
{
	/* STR_ARE_YOU_SURE: */
	"Es tu sûr?",
	/* STR_AUTO_PAUSE_EXPLANATION: */
	"  La fonction Pause automatique va\nvous rappelerez de prendre une pause\n  de jeu chaque 30 minutes environ",
	/* STR_AUTOMATIC_PAUSE: */
	"Pause Automatique",
	/* STR_BACK: */
	"Arrière",
	/* STR_CHECKPOINT: */
	"Poste de contrôle",
	/* STR_CONTINUE: */
	"Continuer",
	/* STR_CREDITS: */
	"Crédits",
	/* STR_LANGUAGE: */
	"Langue",
	/* STR_LANGUAGE_SELECT: */
	"Choix de la langue",
	/* STR_LEVEL: */
	"Niveau",
	/* STR_LEVEL_1_NAME: */
	"Splish Splash Hills",
	/* STR_LEVEL_1_SLOGAN: */
	"\"Nuageux avec un\n risque de pluie\"",
	/* STR_LEVEL_CONQUERED: */
	"Niveau conquis!",
	/* STR_LEVEL_DONE: */
	"Niveau terminé!",
	/* STR_NEW_BEST: */
	"Nouveau Record!",
	/* STR_NEW_GAME: */
	"Nouveau Jeu",
	/* STR_NO: */
	"Non",
	/* STR_OFF: */
	"Desactivé",
	/* STR_ON: */
	"Activé",
	/* STR_OPTIONS: */
	"Options",
	/* STR_PAUSE: */
	"Pause",
	/* STR_PRECAUTION_SCREEN_TEXT: */
	"        IMPORTANT\nPRENEZ CONAISSANCE DE LA\nNOTICE ET DES PRÉCAUTIONS\n    A AVANT DE JOUER",
	/* STR_PRESS_START_BUTTON: */
	"Appuyer sur Start",
	/* STR_PROGRESS_WILL_BE_ERASED: */
	"Tout vôtre progrès sera effacé.",
	/* STR_QUIT_LEVEL: */
	"Quitter Niveau",
	/* STR_SELECT: */
	"Sélectionner",
	/* STR_TAKE_A_REST: */
	"Se il vous plaît, prendre un repos!",
	/* STR_YES: */
	"Oui",
	
};

const LangROMSpec LANGUAGE_FR =
{
	// Language Name
	"Français",

	// Flag Entity
	&FLAG_FRANCE_EN,
	
	// Strings
	(const char**)LANGUAGE_FR_STRINGS
};
